version: '3.8'

services:
  app:
    container_name: nonograms-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # Uncomment the following lines if you want to mount the configuration locally for development/testing
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
