version: '3.8'

services:
  nonograms:
    container_name: ${CONTAINER_NAME:-nonograms}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - npm_public

networks:
  npm_public:
    external: true
